sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.G.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_23_2024/trials/captain_d.first_try.alignment.9.sh
