sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-Difference-Influence.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.G.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step-System-Influence.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.beta.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-Difference-Influence.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.G.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step-System-Influence.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs_redo/trials/two_asvs_redo.charlie.D-Indirect-Traj.9.sh
