sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.2_teams_per_eval.alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.1_team_per_eval.alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/numba_redo/trials/captain_c.numba_redo.3_teams_per_eval.alignment.9.sh
