sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.G.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.2_teams_per_eval.alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.G.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.1_team_per_eval.alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.G.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_11_2024/trials/captain_c.numba.3_teams_per_eval.alignment.9.sh
