sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D-Indirect.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.D.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.no_fitness_bias.G.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D-Indirect.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.D.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.3_teams_per_evaluation.G.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D-Indirect.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.D.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.local.fitness_bias.2_teams_per_evaluation.G.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D-Indirect.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.D.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.no_fitness_bias.G.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D-Indirect.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.D.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.3_teams_per_evaluation.G.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D-Indirect.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.D.9.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.0.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.1.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.2.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.3.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.4.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.5.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.6.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.7.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.8.sh
sbatch ~/influence-multi-objective/sbatch/aug_29_2024/trials/captain_c.observations.global.fitness_bias.2_teams_per_evaluation.G.9.sh
