sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.fitness_critic.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.G.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/sep_30_2024/trials/captain_d.redo2.alignment.9.sh
