#!/bin/bash
sbatch G/trial_0.sh
sbatch D/trial_0.sh
sbatch D-Indirect/trial_0.sh
sbatch G/trial_1.sh
sbatch D/trial_1.sh
sbatch D-Indirect/trial_1.sh
sbatch G/trial_2.sh
sbatch D/trial_2.sh
sbatch D-Indirect/trial_2.sh
sbatch G/trial_3.sh
sbatch D/trial_3.sh
sbatch D-Indirect/trial_3.sh
sbatch G/trial_4.sh
sbatch D/trial_4.sh
sbatch D-Indirect/trial_4.sh
sbatch G/trial_5.sh
sbatch D/trial_5.sh
sbatch D-Indirect/trial_5.sh
sbatch G/trial_6.sh
sbatch D/trial_6.sh
sbatch D-Indirect/trial_6.sh
sbatch G/trial_7.sh
sbatch D/trial_7.sh
sbatch D-Indirect/trial_7.sh
sbatch G/trial_8.sh
sbatch D/trial_8.sh
sbatch D-Indirect/trial_8.sh
sbatch G/trial_9.sh
sbatch D/trial_9.sh
sbatch D-Indirect/trial_9.sh
sbatch G/trial_10.sh
sbatch D/trial_10.sh
sbatch D-Indirect/trial_10.sh
sbatch G/trial_11.sh
sbatch D/trial_11.sh
sbatch D-Indirect/trial_11.sh
sbatch G/trial_12.sh
sbatch D/trial_12.sh
sbatch D-Indirect/trial_12.sh
sbatch G/trial_13.sh
sbatch D/trial_13.sh
sbatch D-Indirect/trial_13.sh
sbatch G/trial_14.sh
sbatch D/trial_14.sh
sbatch D-Indirect/trial_14.sh
sbatch G/trial_15.sh
sbatch D/trial_15.sh
sbatch D-Indirect/trial_15.sh
sbatch G/trial_16.sh
sbatch D/trial_16.sh
sbatch D-Indirect/trial_16.sh
sbatch G/trial_17.sh
sbatch D/trial_17.sh
sbatch D-Indirect/trial_17.sh
sbatch G/trial_18.sh
sbatch D/trial_18.sh
sbatch D-Indirect/trial_18.sh
sbatch G/trial_19.sh
sbatch D/trial_19.sh
sbatch D-Indirect/trial_19.sh
