sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Traj.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.G.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Alignment.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.D-Indirect-Step.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_b.Fitness-Critic.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Traj.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.G.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Alignment.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.D-Indirect-Step.19.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.0.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.1.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.2.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.3.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.4.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.5.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.6.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.7.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.8.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.9.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.10.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.11.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.12.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.13.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.14.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.15.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.16.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.17.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.18.sh
sbatch ~/influence-multi-objective/sbatch/simple_ab/trials/simple_ab.simple_a.Fitness-Critic.19.sh
