ccea:
  evaluation:
    multi_evaluation:
      num_rollouts_per_team: 1
      num_teams_per_evaluation: 1
  mutation:
    independent_probability: 0.5
    mean: 0.0
    std_deviation: 1.0
  num_generations: 10
  selection:
    n_elites_binary_tournament:
      include_elites_in_tournament: false
      n_elites: 5
  subpopulation_size: 30
  weight_initialization:
    lower_bound: -1.0
    upper_bound: 1.0
data:
  save_trajectories:
    num_gens_between_save: 10
    switch: true
env:
  asv_params:
    max_speed: 1.0
    network:
      num_hidden:
      - 10
    num_asv_bins: 4
    num_auv_bins: 4
    num_obstacle_traces: 4
    observation_type: local
    raytrace_distance: 100.0
  asvs:
  - position:
    - 3.5
    - 3.5
  auv_params:
    max_speed: 1.0
  auvs:
  - path:
    - - 3.5
      - 0.5
    - - 0.5
      - 0.5
    - - 0.5
      - 3.5
  collision_step_size: 0.1
  connectivity_grid:
  - - 1
    - 1
    - 1
    - 1
  - - 1
    - 0
    - 0
    - 1
  - - 1
    - 0
    - 0
    - 1
  - - 1
    - 1
    - 1
    - 1
  dt: 1
  pois:
  - observation_radius: 1.0
    position:
    - 0.5
    - 3.5
    value: 1.0
  t_final: 20
  waves:
    x_:
      a: 0.1
      b: 1.0
      c: 0.0
    y_:
      a: 0.1
      b: 1.0
      c: 0.0
experiment:
  num_trials: 10
processing:
  num_threads: 20
  use_multiprocessing: false
rewards:
  asv_reward: global
  auv_reward: none
  distance_threshold: 5.0
  influence_heuristic: line_of_sight
  influence_type: granular
  multi_reward: single
  trajectory_influence_threshold: 0.0
  which_critic: fitness_critic
root_dir: ~/influence-multi-objective
