sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.10.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.11.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.12.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.13.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.14.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.15.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.16.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.17.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.18.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Traj.19.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.0.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.1.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.2.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.3.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.4.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.5.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.6.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.7.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.8.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.9.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.10.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.11.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.12.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.13.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.14.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.15.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.16.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.17.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.18.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D.19.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.0.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.1.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.2.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.3.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.4.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.5.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.6.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.7.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.8.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.9.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.10.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.11.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.12.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.13.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.14.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.15.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.16.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.17.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.18.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.G.19.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.10.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.11.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.12.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.13.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.14.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.15.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.16.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.17.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.18.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Alignment.19.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.0.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.1.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.2.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.3.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.4.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.5.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.6.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.7.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.8.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.9.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.10.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.11.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.12.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.13.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.14.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.15.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.16.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.17.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.18.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.Fitness.19.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.10.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.11.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.12.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.13.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.14.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.15.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.16.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.17.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.18.sh
sbatch ~/influence-multi-objective/sbatch/rewardsaving4/trials/simple_a.rewardsaving4.D-Indirect-Step.19.sh
