sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.G.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.alpha.Fitness-Critic.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.G.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.charlie.Fitness-Critic.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Traj.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.G.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Alignment.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.D-Indirect-Step.9.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.0.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.1.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.2.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.3.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.4.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.5.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.6.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.7.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.8.sh
sbatch ~/influence-multi-objective/sbatch/two_asvs/trials/two_asvs.beta.Fitness-Critic.9.sh
