root_dir: /home/gonzaeve/influence-multi-objective
env:
  dt: 0.1
  collision_step_size: 0.1
  asv:
    max_speed: 1.0
    network:
      num_hidden: [20,20]
  auv:
    max_speed: 1.0
  mission: alpha
  t_final: 100
  pois:
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}