root_dir: /home/gonzaeve/influence-multi-objective
env:
  dt: 1.0
  collision_step_size: 0.1
  num_asvs: 2
  asv:
    max_speed: 1.0
    network:
      num_hidden: [20,20]
    observation_type: global
    raytrace_distance: 100.0
    num_asv_bins: 8
    num_auv_bins: 8
  auv:
    max_speed: 1.0
  mission_dir: /home/gonzaeve/influence-multi-objective/results/captain_c/mission
  t_final: 10
  pois:
    - {value: 1.0, observation_radius: 100.0}
    - {value: 1.0, observation_radius: 100.0}
ccea:
  num_generations: 1000
  weight_initialization:
    lower_bound: 0.0
    upper_bound: 1.0
  subpopulation_size: 50
  selection:
    n_elites_binary_tournament:
      n_elites: 5
      include_elites_in_tournament: True
  mutation:
    mean: 0.0
    std_deviation: 1.0
    independent_probability: 0.5
  evaluation:
    multi_evaluation:
      num_rollouts_per_team: 1
      num_teams_per_evaluation: 2
processing:
  use_multiprocessing: True
  num_threads: 3
data:
  save_trajectories:
    switch: True
    num_gens_between_save: 10
rewards:
  influence_heuristic: line_of_sight
  influence_type: granular
  auv_reward: none
  asv_reward: global
  multi_reward: single
  distance_threshold: 5.0
experiment:
  num_trials: 10
