root_dir: ~/influence-multi-objective
env:
  dt: 0.1
  collision_step_size: 0.1
  num_asvs: 2
  asv:
    max_speed: 1.0
    network:
      num_hidden: [20,20]
  auv:
    max_speed: 1.0
  mission_dir: ~/influence-multi-objective/example_results/mission
  t_final: 100
  pois:
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
ccea:
  mutation:
    mean: 0.0
    std_deviation: 1.0
    independent_probability: 0.5
  num_generations: 10000
  weight_initialization:
    lower_bound: 0.0
    upper_bound: 1.0
  subpopulation_size: 50
  selection:
    n_elites_binary_tournament:
      n_elites: 5
      include_elites_in_tournament: False
  evaluation:
    multi_evaluation:
      num_evaluations_per_team: 1
processing:
  use_multiprocessing: True
  num_threads: 20
data:
  save_trajectories:
    switch: True
    num_gens_between_save: 10
rewards:
  influence_heuristic: line_of_sight
  influence_type: granular
  auv_reward: none
  asv_reward: indirect_difference_team
  multi_reward: single
  distance_threshold: 5.0
experiment:
  num_trials: 10
