root_dir: ~/programs/influence-multi-objective
env:
  dt: 1
  collision_step_size: 0.1
  num_asvs: 2
  asv:
    max_speed: 1.0
    network:
      num_hidden: [20,20]
    observation_type: global
    raytrace_distance: 100.0
    num_asv_bins: 8
    num_auv_bins: 8
    num_obstacle_traces: 8
  auv:
    max_speed: 1.0
  mission_dir: ~/programs/influence-multi-objective/example_results/mission
  t_final: 5
  pois:
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
    - {value: 1.0, observation_radius: 5.0}
ccea:
  mutation:
    mean: 0.0
    std_deviation: 1.0
    independent_probability: 0.5
  num_generations: 10000
  weight_initialization:
    lower_bound: 0.0
    upper_bound: 1.0
  subpopulation_size: 3
  selection:
    n_elites_binary_tournament:
      n_elites: 1
      include_elites_in_tournament: False
  evaluation:
    multi_evaluation:
      num_rollouts_per_team: 1
      num_teams_per_evaluation: 1
processing:
  use_multiprocessing: False
  num_threads: 20
data:
  save_trajectories:
    switch: True
    num_gens_between_save: 10
rewards:
  influence_heuristic: line_of_sight
  influence_type: all_or_nothing
  trajectory_influence_threshold: 0.0
  auv_reward: none
  asv_reward: global
  which_critic: alignment # none, alignment, fitness_critic
  multi_reward: single
  distance_threshold: 5.0
critic:
  state_size: 12
experiment:
  num_trials: 10
