sbatch G/trial_0.sh
sbatch D/trial_0.sh
sbatch D-Indirect-Team/trial_0.sh
sbatch D-Indirect-AUV/trial_0.sh
sbatch G/trial_1.sh
sbatch D/trial_1.sh
sbatch D-Indirect-Team/trial_1.sh
sbatch D-Indirect-AUV/trial_1.sh
sbatch G/trial_2.sh
sbatch D/trial_2.sh
sbatch D-Indirect-Team/trial_2.sh
sbatch D-Indirect-AUV/trial_2.sh
sbatch G/trial_3.sh
sbatch D/trial_3.sh
sbatch D-Indirect-Team/trial_3.sh
sbatch D-Indirect-AUV/trial_3.sh
sbatch G/trial_4.sh
sbatch D/trial_4.sh
sbatch D-Indirect-Team/trial_4.sh
sbatch D-Indirect-AUV/trial_4.sh
sbatch G/trial_5.sh
sbatch D/trial_5.sh
sbatch D-Indirect-Team/trial_5.sh
sbatch D-Indirect-AUV/trial_5.sh
sbatch G/trial_6.sh
sbatch D/trial_6.sh
sbatch D-Indirect-Team/trial_6.sh
sbatch D-Indirect-AUV/trial_6.sh
sbatch G/trial_7.sh
sbatch D/trial_7.sh
sbatch D-Indirect-Team/trial_7.sh
sbatch D-Indirect-AUV/trial_7.sh
sbatch G/trial_8.sh
sbatch D/trial_8.sh
sbatch D-Indirect-Team/trial_8.sh
sbatch D-Indirect-AUV/trial_8.sh
sbatch G/trial_9.sh
sbatch D/trial_9.sh
sbatch D-Indirect-Team/trial_9.sh
sbatch D-Indirect-AUV/trial_9.sh
sbatch G/trial_10.sh
sbatch D/trial_10.sh
sbatch D-Indirect-Team/trial_10.sh
sbatch D-Indirect-AUV/trial_10.sh
sbatch G/trial_11.sh
sbatch D/trial_11.sh
sbatch D-Indirect-Team/trial_11.sh
sbatch D-Indirect-AUV/trial_11.sh
sbatch G/trial_12.sh
sbatch D/trial_12.sh
sbatch D-Indirect-Team/trial_12.sh
sbatch D-Indirect-AUV/trial_12.sh
sbatch G/trial_13.sh
sbatch D/trial_13.sh
sbatch D-Indirect-Team/trial_13.sh
sbatch D-Indirect-AUV/trial_13.sh
sbatch G/trial_14.sh
sbatch D/trial_14.sh
sbatch D-Indirect-Team/trial_14.sh
sbatch D-Indirect-AUV/trial_14.sh
sbatch G/trial_15.sh
sbatch D/trial_15.sh
sbatch D-Indirect-Team/trial_15.sh
sbatch D-Indirect-AUV/trial_15.sh
sbatch G/trial_16.sh
sbatch D/trial_16.sh
sbatch D-Indirect-Team/trial_16.sh
sbatch D-Indirect-AUV/trial_16.sh
sbatch G/trial_17.sh
sbatch D/trial_17.sh
sbatch D-Indirect-Team/trial_17.sh
sbatch D-Indirect-AUV/trial_17.sh
sbatch G/trial_18.sh
sbatch D/trial_18.sh
sbatch D-Indirect-Team/trial_18.sh
sbatch D-Indirect-AUV/trial_18.sh
sbatch G/trial_19.sh
sbatch D/trial_19.sh
sbatch D-Indirect-Team/trial_19.sh
sbatch D-Indirect-AUV/trial_19.sh
