sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Traj.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.G.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Alignment.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.Fitness.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_d.D-Indirect-Step.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Traj.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.G.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Alignment.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.Fitness.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_f.D-Indirect-Step.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Traj.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.G.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Alignment.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.Fitness.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_b.D-Indirect-Step.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Traj.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.G.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Alignment.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.Fitness.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_e.D-Indirect-Step.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Traj.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.G.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Alignment.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.Fitness.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_a.D-Indirect-Step.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Traj.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.G.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Alignment.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.Fitness.19.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.0.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.1.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.2.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.3.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.4.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.5.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.6.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.7.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.8.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.9.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.10.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.11.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.12.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.13.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.14.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.15.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.16.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.17.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.18.sh
sbatch /home/gonzaeve/influence-multi-objective/sbatch/mini-generated/trials/mini-generated.simple_c.D-Indirect-Step.19.sh
